export const FilterList = [
    {name: 'Thriller', genre: 'триллер'},
    {name: 'Horror', genre: 'ужасы'},
    {name: 'Drama', genre: 'драма'},
    {name: 'Action', genre: 'боевик'},
    {name: 'Animated films', genre: 'мультфильм'},
    {name: 'Romantic', genre: 'мелодрама'},
    {name: 'History', genre: 'история'},
    {name: 'Family', genre: 'семейный'},
    {name: 'Criminal', genre: 'криминал'},
    {name: 'Fantastic', genre: 'фантастика'},
    {name: 'Fantasy', genre: 'фэнтези'},
    {name: 'Adventure', genre: 'приключения'},
    {name: 'Comedy', genre: 'комедия'},
];