import './globals.sass'
import Header from './components/header/Header';
import { Open_Sans } from 'next/font/google'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const open_sans = Open_Sans({ subsets: ['latin', 'cyrillic'] })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={open_sans.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
